version: '3.3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.type=single-node
      # - discovery.seed_hosts=es02,es03
      # - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - xpack.security.enabled=true
      # - xpack.security.audit.enabled=true
      # - ELASTICSEARCH_USERNAME=admin
      # - ELASTIC_PASSWORD=es_pw
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana:
    depends_on:
     - es01
    image: "docker.elastic.co/kibana/kibana:7.1.0"
    ports:
     - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
     # - ELASTICSEARCH_URL=http://localhost:9200
     # - ELASTICSEARCH_USERNAME=admin
     # - ELASTICSEARCH_PASSWORD=es_pw
    networks:
     - elastic
  
volumes:
  es_data01:
    driver: local

networks:
  elastic:
    driver: bridge